# Generated by Django 3.0.3 on 2020-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('type_of_match', models.CharField(max_length=20)),
                ('no_of_batsmen', models.PositiveSmallIntegerField()),
                ('right_batsmen', models.SmallIntegerField()),
                ('left_batsmen', models.SmallIntegerField()),
                ('no_of_Pacer', models.PositiveSmallIntegerField()),
                ('pacer_right', models.PositiveSmallIntegerField()),
                ('pacer_left', models.PositiveSmallIntegerField()),
                ('spinner_right', models.PositiveSmallIntegerField()),
                ('spinner_left', models.PositiveSmallIntegerField()),
                ('no_of_wicketkeeper', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
