# Generated by Django 3.0.3 on 2020-04-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='no_of_spinner',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='left_batsmen',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='pacer_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='pacer_right',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='right_batsmen',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='spinner_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='spinner_right',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
