# Generated by Django 3.0.3 on 2020-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20200424_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='type_of_match',
            field=models.CharField(choices=[('T20', 'T20'), ('ODAY', 'ODAY'), ('TEST', 'TEST')], default='T20', max_length=10),
        ),
    ]
