# Generated by Django 3.0.3 on 2020-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_auto_20200424_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('type_of_match', models.CharField(choices=[('T20', 'T20'), ('ODAY', 'ODAY'), ('TEST', 'TEST')], default='T20', max_length=10)),
                ('no_of_batsmen', models.PositiveSmallIntegerField()),
                ('right_batsmen', models.SmallIntegerField(default=0)),
                ('left_batsmen', models.SmallIntegerField(default=0)),
                ('no_of_pacer', models.PositiveSmallIntegerField()),
                ('pacer_right', models.PositiveSmallIntegerField(default=0)),
                ('pacer_left', models.PositiveSmallIntegerField(default=0)),
                ('no_of_spinner', models.PositiveSmallIntegerField(default=0)),
                ('spinner_right', models.PositiveSmallIntegerField(default=0)),
                ('spinner_left', models.PositiveSmallIntegerField(default=0)),
                ('no_of_wicketkeeper', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
